#!/usr/bin/env python3
"""dump.cs → Frida targets + And64InlineHook stubs 自动生成器。

从 Il2CppDumper 输出的 dump.cs 抽取方法签名，
按 hook-discovery-rules.json 的规则匹配 hook 目标，
生成 Frida JS 片段 + C++ 桩函数。

用法：
    python3 dump-cs-generator.py <dump.cs> <rules.json> <output_prefix>

输出：
    <output_prefix>.frida.js        Frida JS 片段
    <output_prefix>.cpp-stubs.h     C++ 桩函数头文件
"""
import json
import re
import sys
from pathlib import Path

if len(sys.argv) != 4:
    sys.exit(__doc__)

DUMP_CS = Path(sys.argv[1])
RULES_JSON = Path(sys.argv[2])
OUT_PREFIX = Path(sys.argv[3])

rules = json.loads(RULES_JSON.read_text())
patterns = []
for cat in rules["categories"]:
    for p in cat["patterns"]:
        patterns.append((cat["name"], p, cat["weight"]))
exclusion_patterns = [re.compile(p) for p in rules["exclusions"][0]["patterns"]]
extraction = rules["extraction_rules"]
max_per_cat = extraction["max_targets_per_category"]

# 解析 dump.cs：offset 和 method 名在 dump.cs 中通常分布在不同行
#   行1: // RVA: 0x... Offset: 0x<HEX> VA: 0x... Slot: N
#   行2: <visibility> <return_type> <MethodName>(<args>) { }
text = DUMP_CS.read_text()
offset_re = re.compile(r"RVA:\s*0x[0-9a-fA-F]+\s+Offset:\s*0x([0-9a-fA-F]+)")
method_re = re.compile(
    r"\b(public|private|internal|protected)\s+[\w<>,\[\]\s]+\s+(\w+)\s*\("
)
class_re = re.compile(r"class\s+(\w+)\b")
visible_re = re.compile(
    r"\b(public|private|internal|protected)\s+[\w<>,\[\]\s]+\s+(\w+)\s*\("
)

# 收集 (offset, visibility, method_name) 平行行
offsets = offset_re.findall(text)
visibilities_methods = visible_re.findall(text)

matched_by_cat = {cat["name"]: [] for cat in rules["categories"]}
all_matched = []

# 类名上下文：当前 method 之前最近的 class 声明
class_ctx = "Unknown"
class_positions = []
for m in class_re.finditer(text):
    class_positions.append((m.start(), m.group(1)))

for i, (offset_hex, (vis, method_name)) in enumerate(
    zip(offsets, visibilities_methods)
):
    if any(p.search(method_name) for p in exclusion_patterns):
        continue
    if len(method_name) < extraction["min_function_name_length"]:
        continue
    # 类名
    method_pos = list(visible_re.finditer(text))[i].start()
    cur_cls = "Unknown"
    for cp, cn in class_positions:
        if cp < method_pos:
            cur_cls = cn
        else:
            break
    # 匹配关键字
    for cat, pat, weight in patterns:
        if pat in method_name:
            entry = {
                "category": cat,
                "class": cur_cls,
                "method": method_name,
                "offset": int(offset_hex, 16),
                "weight": weight,
            }
            if len(matched_by_cat[cat]) < max_per_cat:
                matched_by_cat[cat].append(entry)
            all_matched.append(entry)
            break

# 按权重排序
all_matched.sort(key=lambda x: -x["weight"])

# ────── 生成 Frida JS ──────
frida_lines = [
    "// Auto-generated by dump-cs-generator.py",
    "// Hook targets parsed from dump.cs (Il2CppDumper output)",
    "",
    "const ENCRYPTION_TARGETS = [",
]
for e in matched_by_cat.get("encryption", []):
    frida_lines.append(
        f'    {{ category: "encryption", class: "{e["class"]}", '
        f'method: "{e["method"]}", offset: {e["offset"]} }},'
    )
frida_lines += ["];", "", "const AUTH_TARGETS = ["]
for e in matched_by_cat.get("auth", []):
    frida_lines.append(
        f'    {{ category: "auth", class: "{e["class"]}", '
        f'method: "{e["method"]}", offset: {e["offset"]} }},'
    )
frida_lines += ["];", "", "const NETWORK_TARGETS = ["]
for e in matched_by_cat.get("network", []):
    frida_lines.append(
        f'    {{ category: "network", class: "{e["class"]}", '
        f'method: "{e["method"]}", offset: {e["offset"]} }},'
    )
frida_lines += ["];", ""]

# ────── 生成 C++ 桩头文件 ──────
cpp_lines = [
    "// Auto-generated by dump-cs-generator.py",
    "// And64InlineHook stub declarations",
    "#pragma once",
    "#include <cstdint>",
    "",
]
for e in all_matched:
    if e["category"] not in ("encryption", "auth"):
        continue
    cpp_lines.append(
        f"// {e['category']}: {e['class']}::{e['method']} @ Offset:0x{e['offset']:x}"
    )
    cpp_lines.append(
        f"void* Hooked{e['class']}_{e['method']}(void* __this, void* args);"
    )
    cpp_lines.append(
        f"extern void* Original{e['class']}_{e['method']};"
    )
    cpp_lines.append(
        f"void hook_{e['class']}_{e['method']}(void* baseAddr);"
    )
    cpp_lines.append("")

# 写文件
(OUT_PREFIX.with_suffix(".frida.js")).write_text("\n".join(frida_lines))
(OUT_PREFIX.with_suffix(".cpp-stubs.h")).write_text("\n".join(cpp_lines))

print(f"[+] Total matched: {len(all_matched)}")
for cat, entries in matched_by_cat.items():
    print(f"    {cat}: {len(entries)}")
print(f"[+] Output: {OUT_PREFIX}.frida.js")
print(f"[+] Output: {OUT_PREFIX}.cpp-stubs.h")