#!/usr/bin/env python3
"""generate-hanization-map.py — translations.json → hanization_map.h（native hook 汉化表）。

背景: FlyingGorillaEndlessRunner (2026-08-02) 汉化。native-lib.cpp hook
`LocalizedString.GetLocalizedString()` 返回字符串后，查此表(en→zh)，用 il2cpp_string_new
创建中文字符串替换。

用法:
  python3 generate-hanization-map.py <translations.json> -o <hanization_map.h>

输入格式（translations.json）:
  {"Builder's Hut": "建造者小屋", "Level Complete!": "关卡完成！", ...}

输出（C++ header）:
  #pragma once
  #include <string>
  #include <unordered_map>
  static const std::unordered_map<std::string, std::string> HANIZATION_MAP = {
      {R"(Builder's Hut)", R"(建造者小屋)"},
      ...
  };

注意:
  - key 是 hook 拿到的返回值（英文原值），value 是中文
  - 保留 {0} 占位符（format string，游戏替换参数在获取文本之后）
  - 字符串含 )" 时用分隔符 R"xxx(...)xxx"
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def esc_raw(s: str) -> str:
    """生成安全的 raw string。含 ')' 时用自定义分隔符，避免 R"(...)" 提前终止。"""
    if ')"' not in s and '\\' not in s:
        return f'R"({s})"'
    delim = "x"
    while f'){delim}"' in s:
        delim += "x"
    return f'R"{delim}({s}){delim}"'


def generate(mapping: dict) -> str:
    lines = [
        "#pragma once",
        "#include <string>",
        "#include <unordered_map>",
        "// Auto-generated by generate-hanization-map.py (en→zh-CN)",
        "static const std::unordered_map<std::string, std::string> HANIZATION_MAP = {",
    ]
    for en, zh in mapping.items():
        lines.append(f"    {{{esc_raw(en)}, {esc_raw(zh)}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="translations.json → hanization_map.h")
    ap.add_argument("translations", help="translations.json（en→zh）")
    ap.add_argument("-o", "--out", required=True, help="输出 hanization_map.h 路径")
    args = ap.parse_args()

    t = Path(args.translations)
    if not t.is_file():
        print(f"[ERROR] 不存在: {t}")
        return 1
    mapping = json.loads(t.read_text(encoding="utf-8"))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate(mapping), encoding="utf-8")
    print(f"[OK] {len(mapping)} 条 → {out}")
    print("[INFO] 生成后重跑 gradle 编译 + inject-smali-dex.py --force 生效")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
