#!/usr/bin/env python3
"""init-project-git.py — 给单个处理项目新建"嵌套独立 git 仓库"，用于子阶段提交与回滚。

背景（AGENTS.md 兼容）:
- 父仓库 .gitignore 整棵忽略 crackings/，故每个项目在自身目录内独立 `git init`，
  与父仓库互不干扰（嵌套仓库）。
- 结合「每完成一个子阶段 commit 一次 → 可回滚」的需求：
  本脚本负责初始化；阶段提交由 commit-project-stage.py 负责。

交付:
  1. crackings/<type>/<Name>/.git（若尚未存在）
  2. crackings/<type>/<Name>/.gitignore（项目级，忽略 raw/、project/build 等 GB 级产物，
     只追踪 status.yaml/findings.md/dir-index.yaml/stages 报告/脚本等过程产物）
  3. 首次提交（初始快照），此时已完成的阶段产物一并入库作为基线

用法:
  python3 init-project-git.py --name <Name> [--type <type>] [--force] [--no-commit]
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# 让所有 print 立即 flush，避免与 log_*（stderr）交错时顺序错乱
import functools
print = functools.partial(print, flush=True)  # type: ignore[assignment]

ROOT = Path(__file__).resolve().parents[3]
LIB_DIR = Path(__file__).resolve().parents[0] / "lib"
sys.path.insert(0, str(LIB_DIR))
from common import (  # noqa: F403
    ensure_env,
    log_info,
    log_warn,
    log_success,
    log_error,
    log_step,
)

CRACKINGS_DIR = ROOT / "crackings"


def _fold(s: str) -> str:
    """匹配用折叠：小写 + 去除非字母数字（兼容 'Battle Tank' ↔ 'BattleTank'）。"""
    return "".join(ch for ch in s.lower() if ch.isalnum())


def locate_project(name: str, type_hint: str | None) -> Path | None:
    """在 crackings/ 下定位项目目录 crackings/<type>/<Name>/。

    优先精确 type；否则折叠子串匹配（type 父目录 + 遗留根目录工程）。
    匹配到多个时返回 None 并 warn（需 --type 消歧）。
    """
    kw = _fold(name)
    hits: list[Path] = []
    if not CRACKINGS_DIR.exists():
        return None
    for type_dir in sorted(p for p in CRACKINGS_DIR.iterdir() if p.is_dir()):
        if (type_dir / "status.yaml").exists() or (type_dir / "findings.md").exists():
            # 根目录遗留工程（直接是项目目录而非 type 父目录）
            if kw and kw in _fold(type_dir.name):
                hits.append(type_dir)
            continue
        if type_hint and _fold(type_hint) != _fold(type_dir.name):
            continue
        for proj in sorted(p for p in type_dir.iterdir() if p.is_dir()):
            if kw and kw in _fold(proj.name):
                hits.append(proj)
    if len(hits) == 1:
        return hits[0]
    if len(hits) > 1:
        found = ", ".join(str(h.relative_to(CRACKINGS_DIR)) for h in hits)
        log_warn(f"[init-project-git] 匹配到多个候选: {found}，请用 --type 消歧")
        return None
    # 遗留根目录工程兜底（已在上面环内收集，这里仅为覆盖 name 精确目录）
    cand = CRACKINGS_DIR / name
    if cand.is_dir() and any(cand.iterdir()):
        return cand
    return None


PROJECT_GITIGNORE_TPL = """# auto-generated by init-project-git.py — 项目级忽略（嵌套独立 git 仓库）
# 本文件只忽略"体积大/中间产物"，保证每次子阶段提交轻量、可回滚且有辨识度。
# 若某项目需要追踪被忽略的产物，可在此追加 ! 白名单。

# 解包 / 重打包产物（GB 级）
raw/
raw-*.*
patched/
patched-*.*

# AS 工程构建产物
project/app/build/
project/app/release/
project/app/.cxx/
project/build/
project/.gradle/
project/local.properties
project/*.iml
project/.idea/

# AS 源目录内的原生库/大二进制（构建复制产物，非手艺人改动）
project/app/src/main/jniLibs/
project/app/src/main/lib/
project/app/src/main/assets/bin/
project/app/src/main/javaScaffoding/
project/app/libs/*.jar

# 阶段分析中间产物（dump 等，体积大且可再生成）
stages/*-dump/
stages/*-dump-*/
stages/**/dump/
stages/**/step*-signatures/
stages/**/input/

# 签名 / 密钥（不入库）
*.keystore
*.jks
*.jks.bak

# 二进制 / 临时 / 缓存
*.apk
*.xapk
*.so.backup
*.log
*.bak
*.tmp
*.class
*.dex
*.arsc
*.unity3d
*.mp4
*.ogg
*.mp3
__pycache__/
*.pyc
*.pyo
.pytest_cache/
.mypy_cache/
""".lstrip()


def init_repo(proj_dir: Path, force: bool) -> bool:
    git_dir = proj_dir / ".git"
    if git_dir.exists():
        if not force:
            log_info(f"项目已存在 .git，跳过初始化: {proj_dir.relative_to(ROOT)}")
            return False
        log_warn("--force: 移除已有 .git 后重建")
        subprocess.run(["rm", "-rf", str(git_dir)], check=True)
    log_step(f"在项目目录初始化独立 git 仓库: {proj_dir.relative_to(ROOT)}")
    subprocess.run(["git", "-C", str(proj_dir), "init"], check=True,
                   capture_output=True, text=True)
    # 项目级 .gitignore
    gi = proj_dir / ".gitignore"
    gi.write_text(PROJECT_GITIGNORE_TPL, encoding="utf-8")
    log_info("已生成项目级 .gitignore（忽略 raw/、project/build 等体积产物）")

    # 剥离项目内"内嵌 git 仓库"（如 project/app/src/main/cpp/And64InlineHook 由前一轮
    # 工具克隆而来）。内嵌 .git 会被裸加为 gitlink(子模块引用)，导致该目录内容
    # 无法被本项目追踪与回滚。此处仅删除内嵌 .git 目录，使其成为普通文件。
    embedded = [
        p for p in proj_dir.rglob(".git")
        if p.is_dir() and p.parent != proj_dir  # 排除项目自身的 .git
    ]
    for p in embedded:
        log_warn(f"剥离内嵌 git 仓库: {p.relative_to(proj_dir).parent}")
        subprocess.run(["chmod", "-R", "u+w", str(p.parent)], check=False)
        subprocess.run(["rm", "-rf", str(p)], check=False)
    return True


def first_commit(proj_dir: Path) -> int:
    log_step("首次提交（初始基线快照）")
    subprocess.run(["git", "-C", str(proj_dir), "add", "-A"], check=True)
    r = subprocess.run(
        ["git", "-C", str(proj_dir), "commit",
         "-m", "init: project baseline (pre-stage-01)"],
        capture_output=True, text=True,
    )
    if r.returncode == 0:
        log_success("首次提交完成")
        # 统计
        lst = subprocess.run(["git", "-C", str(proj_dir), "ls-files"], capture_output=True, text=True)
        n = len(lst.stdout.splitlines())
        log_info(f"入库文件数: {n}")
        return 0
    # 无变更可提交（git commit 返回 1），非错误
    log_warn("首次提交: 无变更可提交（或仅空仓库）" if r.returncode == 1 else
             f"首次提交失败: {r.stderr.strip()}")
    return 0 if r.returncode == 1 else 1


def main() -> int:
    ensure_env()
    ap = argparse.ArgumentParser(description="给单个处理项目初始化嵌套独立 git 仓库")
    ap.add_argument("--name", required=True, help="项目名（CamelCase，折叠匹配 crackings/）")
    ap.add_argument("--type", default=None, help="引擎类型父目录（crackings/<type>/），多候选时消歧")
    ap.add_argument("--force", action="store_true", help="已有 .git 时移除重建")
    ap.add_argument("--no-commit", action="store_true", help="只 init + 生成 .gitignore，不做首次提交")
    args = ap.parse_args()

    proj_dir = locate_project(args.name, args.type)
    if not proj_dir:
        # 尝试精确目录
        cand = CRACKINGS_DIR / args.name
        if cand.is_dir():
            proj_dir = cand
        else:
            log_error(f"未定位到项目: crackings/**/{args.name}，请检查项目名或 --type")
            return 1

    created = init_repo(proj_dir, args.force)
    if not args.no_commit:
        rc = first_commit(proj_dir)
    else:
        rc = 0
        log_info("--no-commit: 已 init，跳过首次提交")
    log_success("[init-project-git] 完成")
    return rc


if __name__ == "__main__":
    sys.exit(main())