#!/usr/bin/env python3
"""
sub-stage-hook-plan.py — IL2CPP Hook 点与转发计划生成。

职责：
- 读取 `crackings/<Name>/stages/03-fn-analyze/step1-signatures/dump/dump.cs`
- 用启发式正则匹配 `IAP`/`Ad`/`Premium`/`Localization` 类别
- 输出 `crackings/<Name>/stages/03-fn-analyze/step2-hook-plan/hook-plan.yaml`

产物契约：
- hook-plan.yaml 含 ≥4 项 hook 候选（按类别）
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import datetime as _dt
from pathlib import Path

ROOT = Path(__file__).resolve().parents[5]
SCRIPT_PKG = ROOT / "skills" / "strategy" / "il2cpp-strategy-skill" / "scripts"
sys.path.insert(0, str(SCRIPT_PKG))
import importlib.util as _ilu

_spc = _ilu.spec_from_file_location(
    "stage_common_runtime", str(SCRIPT_PKG / "lib" / "stage_common.py")
)
_sc = _ilu.module_from_spec(_spc)
assert _spc.loader is not None
_spc.loader.exec_module(_sc)

ensure_dir = _sc.ensure_dir
fatal = _sc.fatal
log_step = _sc.log_step
log_info = _sc.log_info
log_warn = _sc.log_warn
log_success = _sc.log_success
append_status = _sc.append_status
append_tool_call = _sc.append_tool_call
stage_out = _sc.stage_out

CATEGORY_PATTERNS = {
    "IAP": re.compile(r"\b(ProcessPurchase|InitiatePurchase|OnInitialized|PurchaseHandler|BillingClient)\b", re.IGNORECASE),
    "Ad": re.compile(r"\b(ShowRewardedVideo|RewardVideo|ShowAd|OnAdRewarded|RewardedVideoOnAdRewardedEvent|LevelPlay)\b", re.IGNORECASE),
    "Premium": re.compile(r"\b(SetPremiumMode|UnlockPremuim|BuyPremiumPass|SetArmorPurchased|Unlock)\b", re.IGNORECASE),
    "Localization": re.compile(r"\b(set_text|get_text|SetLocalization|LocalizationKey)\b", re.IGNORECASE),
}

# Match both "// RVA: 0x..." (Il2CppDumper) and "// 0x...-0x..." (Il2CppInspectorRedux)
RVA_PATTERN = re.compile(r"//\s*(?:RVA:\s*)?0x([0-9A-Fa-f]+)")
SIG_PATTERN = re.compile(r"^[\s]*(public|private|internal)?\s*([\w<>,\s\[\]]+?)\s+(\w+)\(([^)]*)\)", re.MULTILINE)


def _resolve_name() -> str:
    name = os.environ.get("NAME", "").strip()
    if not name:
        fatal("环境变量 NAME 未设置；请通过 crack.py 调度")
    return name


def parse_dump(dump_path: Path) -> list[dict]:
    text = dump_path.read_text(encoding="utf-8", errors="ignore")
    hooks: list[dict] = []
    lines = text.splitlines()
    for idx, line in enumerate(lines):
        m = RVA_PATTERN.search(line)
        if not m:
            continue
        rva = int(m.group(1), 16)
        # Il2CppInspectorRedux: RVA and signature on the SAME line
        # e.g. "public bool ShowAd(...); // 0x013531D0-0x01353214"
        sig_line = line.strip()
        # Il2CppDumper: RVA on one line, signature on the NEXT line
        if not any(c in sig_line for c in ('(', ')')):
            if idx + 1 >= len(lines):
                continue
            sig_line = lines[idx + 1].strip()
        for cat, pat in CATEGORY_PATTERNS.items():
            if pat.search(sig_line):
                tag_match = re.search(r"\b(\w+)\s*\(", sig_line)
                tag = tag_match.group(1) if tag_match else f"hook_{len(hooks)}"
                hooks.append(
                    {
                        "tag": f"{cat}_{tag}_{len(hooks)}",
                        "rva": f"0x{rva:X}",
                        "rva_int": rva,
                        "category": cat,
                        "signature": sig_line,
                        "desc": f"{cat} -> {tag}",
                    }
                )
                break
        if len(hooks) >= 32:
            break
    return hooks


def dump_to_yaml(hooks: list[dict]) -> str:
    """生成 YAML 格式的 hook-plan.yaml。

    格式：
        # generated by sub-stage-hook-plan.py
        schema_version: 1
        generated_at: "..."
        count: N

        hooks:
          - tag: "..."
            rva: "0x..."
            rva_int: N
            category: "..."
            signature: "..."
            desc: "..."
    """
    lines: list[str] = []
    lines.append("# generated by sub-stage-hook-plan.py")
    lines.append(f"# generated_at: {_dt.datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"schema_version: 1")
    lines.append(f"count: {len(hooks)}")
    lines.append("")
    lines.append("hooks:")
    for h in hooks:
        lines.append(f"  - tag: \"{h['tag']}\"")
        lines.append(f"    rva: \"{h['rva']}\"")
        lines.append(f"    rva_int: {h['rva_int']}")
        lines.append(f"    category: \"{h['category']}\"")
        # Multi-line signature: fold to first line for YAML safety
        sig = h['signature'].replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ')
        lines.append(f"    signature: \"{sig}\"")
        lines.append(f"    desc: \"{h['desc']}\"")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="IL2CPP Hook 计划生成（YAML 输出）")
    parser.add_argument("--max", type=int, default=12, help="最大 hook 数")
    # [FLOWFIX 2026-08-19] 与 stage-04 _run_script 通用调用兼容：
    # 该 caller 会为所有 helper 追加 --name/--type；本脚本从 env 解析 name/type，
    # 这两个参数仅占用位（consume 掉避免 argparse unrecognized arguments）。
    parser.add_argument("--name", default="", help="（兼容占位）项目名，实际从 env NAME 读取")
    parser.add_argument("--type", default="", help="（兼容占位）引擎类型，实际从 env TYPE 读取")
    args = parser.parse_args()

    name = _resolve_name()
    type_arg = os.environ.get("TYPE", "").strip()
    if type_arg:
        base = ROOT / "crackings" / type_arg / name
    else:
        base = ROOT / "crackings" / name

    dump_cs = base / "stages" / "03-fn-analyze" / "step1-signatures" / "dump" / "dump.cs"
    if not dump_cs.is_file():
        log_warn(f"dump.cs 缺失: {dump_cs}; 阶段 03 step1 必须先跑")
        return 1

    sd = stage_out(name, "03-fn-analyze")
    sd_hook_plan = sd / "step2-hook-plan"
    ensure_dir(sd_hook_plan)
    log_step("hook-plan 生成（YAML 格式）")
    hooks = parse_dump(dump_cs)[: args.max]

    plan_yaml = sd_hook_plan / "hook-plan.yaml"
    plan_yaml.write_text(dump_to_yaml(hooks), encoding="utf-8")

    if len(hooks) < 4:
        log_warn(f"hook 候选 < 4 ({len(hooks)})；检查 dump.cs 是否完整")
        return 1
    log_success(f"hook-plan.yaml ({len(hooks)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
